/*
 * vmysql
 *
 * <br/>https://ncloud.beta-apigw.gov-ntruss.com/vmysql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmysql

type CloudMysqlUserList struct {

	// CloudMysqlDBUser리스트
	CloudMysqlUserList []*CloudMysqlUser `json:"cloudMysqlUserList,omitempty"`
}
