/*
 * vmysql
 *
 * <br/>https://ncloud.beta-apigw.gov-ntruss.com/vmysql/v2
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vmysql

type CloudMysqlBackupList struct {

	// CloudMysql백업리스트
	CloudMysqlBackupList []*CloudMysqlBackup `json:"cloudMysqlBackupList,omitempty"`
}
